### ISSUE TITLE
Habitat Builder not working on MS and newer Subnautica versions

### ISSUE THREAD

**Issue by PixeoGames** [SubnauticaModding/SMLHelper#251]
I can open the Construction UI and so far, modded items do appear (cyclops docking mod) but clicking on any buildable items, vanilla or not causes nothing to happen. The UI stays open, but it's as if clicks do not register.
I Have gone and removed all other mods, testing 2 versions with SMLHelper installed, and a version with only QMM installed, and if i install SMLH it causes the habitat builder to stop working as described above.
I would completely understand if this isn't going to be patched until Steam and Epic versions update, but if you are willing to update and attempt to fix this bug, I will supply anything I'm able to in order to get it fixed
Attached files are the QMM log, after running the game with only SMLH
[qmodmanager_log-Subnautica.txt](https://github.com/SubnauticaModding/SMLHelper/files/7656889/qmodmanager_log-Subnautica.txt)

**Comment by Metious** [comment]
Hello, thanks for the report. try out this build and let me know how it goes:
[SMLHelper_SN.EXP.zip](https://github.com/SubnauticaModding/SMLHelper/files/7586750/SMLHelper_SN.EXP.zip)

**Comment by PixeoGames** [comment]
I Seem to be unable to get QMM to load at all today, which sounds about right with the issues I've been having with the Microsoft store version so far. Only change is a pc restart. Tried a reinstall, restart, etc. and I could not get it to work. Last night I did get a massive save corruption and lost roughly 30h of progress on which I just gave up on that version and bought the steam version which has been working flawlessly this entire time.
I am sorry about any inconvenience that this caused, but I do hope at a future point someone who does have the issues I had finds this and that file ends up working for them. I would try to continue helping to get this to a working point for others in the future, but I just cannot figure out within the 30m of testing I did why QMM no longer loads at all.

**Comment by PixeoGames** [comment]
On a better and new note, on the base steam version i did notice heavy stuttering in game when in bases and the lifepod and I couldn't find a mod that could fix it. (This appears to be a known issue from a google search) Updating to the latest experimental build of Subnautica did fix the stutter issue, it broke the normal version of SMLH I installed off of vortex. This version did load, and most mods did load and seem to work (only one i can see so far is the map mod not loading), yet the bug with the habitat builder not working is present. This should be easier for you to diagnose, as it seems to not only be present on the MS store version, but on all later builds of Subnautica, including the experimental steam version.

**Comment by Metious** [comment]
Subnautica Microsoft Store version and Subnautica Experimental are both on as we call it, the "ModApocalypse" changes. that is where Subnautica receives a major overhaul in GameObjects loading, which will make a fair amount of mods to break.
Unfortunately as a mod consumer, don't expect any mod to work on those versions until they hit the stable branch of Subnautica.
As for QModManager itself, try out this build: [QModManager_4.3.0_Subnautica_Experimental_Setup.zip](https://github.com/SubnauticaModding/SMLHelper/files/7668106/QModManager_4.3.0_Subnautica_Experimental_Setup.zip) (for Microsoft Store, grab the Below Zero Stable build from [QModManager's 4.3.0 releases page](https://github.com/SubnauticaModding/QModManager/releases/tag/v4.3)).
Generally speaking, the experimental QModManager and SMLHelper builds are actually made for authors to check if their mods are broken and potentially have a fix for them before the patches are dropped on the stable branch, so they can just publish the fixes as soon as possible.
