### ISSUE TITLE
Not build

### ISSUE THREAD

**Issue by valador** [SubnauticaModding/SMLHelper#283]
Error CS0117 "uGUI_SceneLoading" does not contain a definition for "BeginAsyncSceneLoad"
what am I doing wrong?

**Comment by desperationfighter** [comment]
1. Give very low informations what you do....
That means. You try to compile SML yourself ?
What Game Version do you try to Compile ? (SN/SN EXP/BZ/BZ EXP)
What Release Version you want to Compile from Game and SML.
(For example if you have the Gamepass version you will never get it done as it not work currently)
Where do you get the Error? (On Syntax Check/On Build/In Logfile)
Did you Modify something or do you compile as it is ?

2. Regardless of the first point.
Make sure to use the correct SN File for Compile.
Update your game and use the correct Build setup.
It maybe helps to delete the SN File once in your Project and start over.

3. If the Error still exist. Give Feedback where the error occurs.
Behind the error you normally get the information what File and Line is causing it. So we can follow what code throw the Error.

4. You may visit the Subnautica Modding Discord as its easier to help and discuss and there are also more people around
https://discord.gg/UpWuWwq -> Mod Making Channel

5. In case there is no special reason behind that all. You can also just take the compiled version from releases.

**Comment by valador** [comment]
I try to build stable and exp, error similar, if i comment in IngameMenuPatcher.cs line:
`harmony.Patch(AccessTools.Method(typeof(uGUI_SceneLoading), nameof(uGUI_SceneLoading.BeginAsyncSceneLoad)),
                postfix: new HarmonyMethod(AccessTools.Method(typeof(IngameMenuPatcher), nameof(InvokeLoadEvents))));`
Everything build perfect.
