### ISSUE TITLE
The following mod could not be loaded: SMLHelper. Check the log for more information.

### ISSUE THREAD

**Issue by D3FAU4T** [SubnauticaModding/SMLHelper#301]
Game Version: January 2023, Build 49483
BepInEx 5.4.19.0 - SubnauticaZero
Using latest version of SMLHelper
QModManager log dump:  [qmodmanager_log-SubnauticaZero.txt](https://github.com/SubnauticaModding/SMLHelper/files/10759319/qmodmanager_log-SubnauticaZero.txt)

Error lines in the Log dump:
- Line 41
- Line 47 and 48
- Line 362 to 378
- Line 436

![image](https://user-images.githubusercontent.com/89858397/219455076-5ebff9f5-ce2e-4e37-8dec-0fa312d8f292.png)

**Comment by RamuneNeptune** [comment]
Hi @D3FAU4T, refer to:
- Line 47-48
- Line 74
- Line 76
- Line 260

https://isthereanydeal.com/game/subnauticabelowzero/info/

**Comment by D3FAU4T** [comment]
@RamuneNeptune Would the mod not work at all in a pirated copy?

**Comment by RamuneNeptune** [comment]
@D3FAU4T, pirated copies of the game very typically have issues with mods, the fix here is to purchase the game, and if you do that we are also able to help with any further (legitimate) issues via the [Subnautica Modding discord server](https://discord.gg/UpWuWwq)
